### ISSUE TITLE
Bug:  Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by zanodor** [platers/obsidian-linter#1025]
Latest version.
Reverting to 1.22.0 fixed issue. 

Sorry, I re-started and forgot to add the full console report. 
Just thought I'd mention (my genius solution).

**Comment by tim-hilde** [comment]
This is the console report:

```
[Obsidian Linter] Lint File Error in File 'Gutachten Bachelorarbeit El-Mohamad.md':
TypeError Cannot read properties of undefined (reading 'trim')
TypeError: Cannot read properties of undefined (reading 'trim')
    at eval (plugin:obsidian-linter:2852:3633)
    at Le (plugin:obsidian-linter:118:1205)
    at lo.runCustomRegexReplacement (plugin:obsidian-linter:2852:3423)
    at lo.lintText (plugin:obsidian-linter:2852:1657)
    at Oo.runLinterEditor (plugin:obsidian-linter:2861:7921)
    at originalSaveCallback.n.callback (plugin:obsidian-linter:2861:4041)
    at Jq (app://obsidian.md/app.js:1:1792124)
    at e.executeCommand (app://obsidian.md/app.js:1:1793657)
    at e.eval (plugin:obsidian-kanban:77:14406)
    at e.o [as executeCommand] (plugin:obsidian-kanban:23:77313)
```

**Comment by pjkaufman** [comment]
Interesting. Could you provide your `data..json` @tim-hilde  or @zanodor ?

**Comment by tim-hilde** [comment]
Sure
[data.json](https://github.com/platers/obsidian-linter/files/14420832/data.json)

**Comment by jiyee** [comment]
+1

**Comment by pjkaufman** [comment]
I think I see the issue. It is related to the label being blank. I forgot to account for that being undefined.

**Comment by pjkaufman** [comment]
I believe I have a fix for this. I am not sure about the severity of the issue, but it affects all custom replacements that do not have value for their label (not even an empty string). I did not account for that happening in the logic in the code for debug messages.

**Comment by pjkaufman** [comment]
It should be feasible to work around this by adding a label to any missing one and then removing the label.

**Comment by pjkaufman** [comment]
This change should now be on master and be going out in the next release. Please let us know if that is not the case.
