### ISSUE TITLE
Cannot Lint all files in this vault

### ISSUE THREAD

**Issue by htyeim** [platers/obsidian-linter#206]
`Linter: Lint all fiels in the vault` seems break recently. The Console shows theerror message from (`alt+cmd+i`) below:
```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'app')
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:28551:36)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:31:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app.js:1:1), <anonymous>:27:12)
    at runLinterAllFiles (eval at <anonymous> (app.js:1:1), <anonymous>:28550:16)
    at LintConfirmationModal.eval (eval at <anonymous> (app.js:1:1), <anonymous>:28772:23)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:31:71)
    at new Promise (<anonymous>)
```

At first, I though it might be related to some notes non-standard content, so I created a new vault with only one simple note. However, the command still broke in the new vault....

I am not sure if it is a bug or am I misunderstand some settings?

**Comment by pjkaufman** [comment]
That may be a bug. I will create a new vault and test it. There was a recent refactor made to that portion of the code that may have broken lint all files in vault.

**Comment by pjkaufman** [comment]
I am not getting the error message, but I am seeing it is not linting all files. I am looking into what may be causing the issue. But for some reason getting the list of markdown files is failing for me locally. It just seems to stall.

**Comment by pjkaufman** [comment]
I can get the logic to work if I go ahead and run the lint command from outside of the modal, so I wonder if something about the context and the `this` value got changed. I will swap how things are working and see what happens.

**Comment by pjkaufman** [comment]
If you would like, you can go ahead and install the plugin from github and see if it fixes your issue.

**Comment by htyeim** [comment]
Yes, the problem has been solved. Thanks!!
